# Generated by Django 4.2.29 on 2026-04-22 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='stock',
            field=models.IntegerField(default=10),
        ),
    ]
